apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pet-battle-ui-pipeline
spec:
  workspaces:
    - name: shared-workspace
    - name: argocd-env-secret
    - name: git-auth-secret
  params:
  - name: APPLICATION_NAME
    type: string
    default: ""
  - name: GIT_URL
    type: string
    default: ""
  - name: GIT_REVISION
    type: string
    default: "master"
  - name: GIT_REF
    type: string
    default: "refs/heads/master"
  - name: GIT_SHORT_REVISION
    type: string
    default: ""
  - name: GIT_BRANCH
    type: string
    default: "master"
  - name: HELM_CHART_VERSION
    type: string
    default: ""
  - name: HELM_OVERWRITE_VALUES
    type: string
    default: "image_repository=image-registry.openshift-image-registry.svc:5000,image_version=$(params.GIT_SHORT_REVISION),image_namespace=$(params.DEV_NAMESPACE)"
  - name: NPM_MIRROR_URL
    type: string
    default: "http://sonatype-nexus-service.labs-ci-cd.svc.cluster.local:8081/repository/labs-npm"
  - name: BUILD_NAMESPACE
    type: string
    default: "labs-ci-cd"
  - name: DEV_NAMESPACE
    type: string
    default: "labs-dev"
  - name: TEST_NAMESPACE
    type: string
    default: "labs-test"
  - name: STAGE_NAMESPACE
    type: string
    default: "labs-staging"
  - name: APP_OF_APPS_DEV_KEY
    type: string
    default: ""
  - name: APP_OF_APPS_TEST_KEY
    type: string
    default: ""
  - name: APP_OF_APPS_STAGE_KEY
    type: string
    default: ""
  tasks:
    - name: fetch-app-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.GIT_URL)"
        - name: revision
          value: "$(params.GIT_REVISION)"
        - name: refspec
          value: "$(params.GIT_REF)"
        - name: subdirectory
          value: "$(params.APPLICATION_NAME)/$(params.GIT_REF)"
        - name: deleteExisting
          value: "true"

    - name: fetch-cicd-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "https://github.com/petbattle/pb-ci-cd.git"
        - name: revision
          value: "main"
        - name: subdirectory
          value: "$(params.APPLICATION_NAME)/cicd"
        - name: deleteExisting
          value: "true"
      runAfter:
        - fetch-app-repository

    - name: npm-install
      taskRef:
        name: nodejs
      params:
        - name: NPM_MIRROR_URL
          value: "$(params.NPM_MIRROR_URL)"
        - name: GOALS
          value:
            - "install"
        - name: WORK_DIRECTORY
          value: "$(params.APPLICATION_NAME)/$(params.GIT_REF)"
      runAfter:
        - fetch-cicd-repository
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: npm-test
      taskRef:
        name: nodejs
      params:
        - name: NPM_MIRROR_URL
          value: "$(params.NPM_MIRROR_URL)"
        - name: GOALS
          value:
            - "run"
            - "test:ci"
        - name: WORK_DIRECTORY
          value: "$(params.APPLICATION_NAME)/$(params.GIT_REF)"
      runAfter:
        - npm-install
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: code-analysis
      taskRef:
        name: nodejs
      params:
        - name: NPM_MIRROR_URL
          value: "$(params.NPM_MIRROR_URL)"
        - name: GOALS
          value:
            - "run"
            - "sonar"
        - name: WORK_DIRECTORY
          value: "$(params.APPLICATION_NAME)/$(params.GIT_REF)"
      runAfter:
        - npm-test
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: npm-run-build
      taskRef:
        name: nodejs
      params:
        - name: NPM_MIRROR_URL
          value: "$(params.NPM_MIRROR_URL)"
        - name: GOALS
          value:
            - "run"
            - "build"
        - name: WORK_DIRECTORY
          value: "$(params.APPLICATION_NAME)/$(params.GIT_REF)"
      runAfter:
        - code-analysis
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: kustomize-build-config
      taskRef:
        name: openshift-kustomize
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: SCRIPT
          value: "kustomize build $1 | oc apply -f-"
        - name: ARGS
          value:
            - "$(params.APPLICATION_NAME)/cicd/applications/build"
      runAfter:
        - npm-run-build

    - name: oc-start-build
      taskRef:
        name: openshift-client
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: SCRIPT
          value: "oc start-build $1 --from-dir=$(params.APPLICATION_NAME)/$(params.GIT_REF) --follow"
        - name: ARGS
          value:
            - "$(params.APPLICATION_NAME)"
      runAfter:
        - kustomize-build-config

    - name: upload-chart
      retries: 1
      taskRef:
        name: helm-upload-chart
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
      - name: WORK_DIRECTORY
        value: "$(params.APPLICATION_NAME)/$(params.GIT_REF)"
      runAfter:
        - oc-start-build

    - name: oc-tag-image-dev
      taskRef:
        name: openshift-client
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: SCRIPT
          value: "oc -n $3 tag $1:latest $2/$1:$4" # tag by git revision
        - name: ARGS
          value:
            - "$(params.APPLICATION_NAME)"
            - "$(params.DEV_NAMESPACE)"
            - "$(params.BUILD_NAMESPACE)"
            - "$(params.GIT_SHORT_REVISION)"
      runAfter:
        - upload-chart

    - name: oc-tag-image-test
      when:
        - Input: "$(params.GIT_BRANCH)"
          Operator: in
          Values: ["master"]
      taskRef:
        name: openshift-client
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: SCRIPT
          value: "oc -n $3 tag $1:latest $2/$1:$4" # tag by git revision
        - name: ARGS
          value:
            - "$(params.APPLICATION_NAME)"
            - "$(params.TEST_NAMESPACE)"
            - "$(params.BUILD_NAMESPACE)"
            - "$(params.GIT_SHORT_REVISION)"
      runAfter:
        - upload-chart

    - name: oc-tag-image-stage
      when:
        - Input: "$(params.GIT_BRANCH)"
          Operator: in
          Values: ["master"]
      taskRef:
        name: openshift-client
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: SCRIPT
          value: "oc -n $3 tag $1:latest $2/$1:$4" # tag by git revision
        - name: ARGS
          value:
            - "$(params.APPLICATION_NAME)"
            - "$(params.STAGE_NAMESPACE)"
            - "$(params.BUILD_NAMESPACE)"
            - "$(params.GIT_SHORT_REVISION)"
      runAfter:
        - upload-chart

    - name: helm-install-apps-dev # branches only deploy to dev
      when:
        - Input: "$(params.GIT_BRANCH)"
          Operator: notin
          Values: ["master"]
      taskRef:
        name: helm-upgrade-from-repo
      params:
        - name: helm_repo_name
          value: "nexus"
        - name: helm_repo_url
          value: "http://sonatype-nexus-service:8081/repository/helm-charts/"
        - name: chart_name
          value: "$(params.APPLICATION_NAME)"
        - name: release_name
          value: "$(params.GIT_BRANCH)"
        - name: release_version
          value: "$(params.HELM_CHART_VERSION)"
        - name: release_namespace
          value: "$(params.DEV_NAMESPACE)"
        - name: overwrite_values
          value: "image_repository=image-registry.openshift-image-registry.svc:5000,image_version=$(params.GIT_SHORT_REVISION),image_namespace=$(params.DEV_NAMESPACE)"
      runAfter:
        - oc-tag-image-dev

    - name: git-commit-test
      retries: 1
      taskRef:
        name: git-commit-argo-versions
      workspaces:
        - name: git-auth-secret
          workspace: git-auth-secret
        - name: output
          workspace: shared-workspace
      params:
      - name: APPLICATION_NAME
        value: "$(params.APPLICATION_NAME)"
      - name: WORK_DIRECTORY
        value: "$(params.APPLICATION_NAME)/cicd"
      - name: GIT_TAG
        value: "$(params.GIT_REVISION)"
      - name: APP_OF_APPS_KEY
        value: "$(params.APP_OF_APPS_TEST_KEY)"
      - name: ARGOCD_CONFIG_REPO_PATH
        value: "applications/deployment/values-applications-test.yaml"
      runAfter:
      - oc-tag-image-test

    - name: helm-argocd-apps-test
      when:
        - Input: "$(params.GIT_BRANCH)"
          Operator: in
          Values: ["master"]
      taskRef:
        name: helm-template-from-source
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: charts_dir
          value: "$(params.APPLICATION_NAME)/cicd/applications/deployment"
        - name: values_file
          value: argo-app-of-apps-test.yaml
        - name: release_name
          value: my
        - name: target_namespace
          value: "$(params.BUILD_NAMESPACE)"
        - name: overwrite_values
          value: "foo=bar"
      runAfter:
        - git-commit-test

    - name: argocd-sync-application-test
      retries: 3
      taskRef:
        name: argocd-sync-and-wait
      workspaces:
      - name: argocd-env-secret
        workspace: argocd-env-secret
      params:
      - name: application-name
        value: "-l app.kubernetes.io/instance=$(params.APPLICATION_NAME)"
      - name: flags
        value: --insecure
      - name: revision
        value: "$(params.HELM_CHART_VERSION)"
      runAfter:
      - helm-argocd-apps-test

    - name: git-commit-stage
      retries: 1
      taskRef:
        name: git-commit-argo-versions
      workspaces:
        - name: git-auth-secret
          workspace: git-auth-secret
        - name: output
          workspace: shared-workspace
      params:
      - name: APPLICATION_NAME
        value: "$(params.APPLICATION_NAME)"
      - name: WORK_DIRECTORY
        value: "$(params.APPLICATION_NAME)/cicd"
      - name: GIT_TAG
        value: "$(params.GIT_REVISION)"
      - name: APP_OF_APPS_KEY
        value: "$(params.APP_OF_APPS_STAGE_KEY)"
      - name: ARGOCD_CONFIG_REPO_PATH
        value: "applications/deployment/values-applications-stage.yaml"
      runAfter:
      - oc-tag-image-stage

    - name: helm-argocd-apps-stage
      when:
        - Input: "$(params.GIT_BRANCH)"
          Operator: in
          Values: ["master"]
      taskRef:
        name: helm-template-from-source
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: charts_dir
          value: "$(params.APPLICATION_NAME)/cicd/applications/deployment"
        - name: values_file
          value: argo-app-of-apps-stage.yaml
        - name: release_name
          value: my
        - name: target_namespace
          value: "$(params.BUILD_NAMESPACE)"
        - name: overwrite_values
          value: "foo=bar"
      runAfter:
        - git-commit-stage

    - name: argocd-sync-application-stage
      retries: 3
      taskRef:
        name: argocd-sync-and-wait
      workspaces:
      - name: argocd-env-secret
        workspace: argocd-env-secret
      params:
      - name: application-name
        value: "l app.kubernetes.io/instance=$(params.APPLICATION_NAME)"
      - name: flags
        value: --insecure
      - name: revision
        value: "$(params.HELM_CHART_VERSION)"
      runAfter:
      - helm-argocd-apps-stage
